### ISSUE TITLE
does it run faster than sklearn dbscan ?

### ISSUE THREAD

**Issue by lonlonago** [Markus-Goetz/hpdbscan#1]
RT.
thanks for your work, could you give a run time compare report than other dbscan in README?

**Comment by Markus-Goetz** [comment]
Helmhut Neukirchen for the University of Iceland did a performance evaluation [1] comparing it to other parallel implementations and the single-node implementation in ELKI. Michael Hasler did an evaluation comparing ELKI with sklearn [2], where sklearn is faster than ELKI. Based on the numbers given there, HPDBSCAN should outperform sklearn. A thorough evaluation for the README still needs to be done though.

[1] [https://notendur.hi.is/~helmut/publications/VHI-01-2016.pdf](https://notendur.hi.is/~helmut/publications/VHI-01-2016.pdf)
[2] [https://pdfs.semanticscholar.org/0c4c/3ddb6820cf59d29dc1dec7c71a4a6eecee27.pdf](https://pdfs.semanticscholar.org/0c4c/3ddb6820cf59d29dc1dec7c71a4a6eecee27.pdf)

**Comment by lonlonago** [comment]
thanks a lot!

**Comment by Markus-Goetz** [comment]
Added a benchmarking suite and some results to the README. Feel free to extend it and issue a PR if you are interested. I assume that this issue is resolved.
